# $Id: mkproto.awk,v 1.2 2005/11/16 20:44:57 rick Exp $
# Generates a file of C prototypes
# Additional information for Doxygen file definition added
# Add any type definitions to regular expressions below.
#
# To exclude a prototype, add whitespace before first definition.
# functions which start with static and extern are also excluded.
# Similar to ancient Unix command mkproto. Many versions of this are public
# around the net.
#
#Copyright (c) 2003-2004 Alan R. Weiss and Rick Foos (Copyright Holders)
#
#All Rights Reserved.  
#
#This licensed program product is made available to Surfbench (Licensee) 
#and Surfbench's Sub-licensees on a non-exclusive, transferable basis, 
#subject to the Transfer Agreement.  Title to this licensed program product 
#and all files, technology, and patents pending remains with the Copyright Holders.
#
#No title, property rights or copyright in the Software or in any modifications 
#of the Software shall pass to the Licensee or Sub-licensee without agreement 
#by the Copyright Holders. The Software is licensed, not sold. By installing, 
#copying, or otherwise using the Software, you agree to be bound by the terms 
#and conditions of this license.
#
#The Licensee and Sub-licensee understands and agrees that the Benchmarks 
#licensed by Copyright Holders hereunder (including methods or concepts 
#utilized therein) contain certain information that is confidential and 
#proprietary which the Licensee and Sub-licensee expressly agrees to retain 
#in the strictest confidence and to use only in conjunction with the Benchmarks 
#pursuant to the terms of this Agreement.  The Licensee and Sub-licensee further
#agrees to keep the source code and all related documentation confidential and 
#not to disclose such source code and/or related documentation to any third party.
#
#The Licensee and Sub-licensee, and any READER of this code is subject to all 
#agreements and licenses of Surfbench.
#
#Where any third party software is included in this the Software, its use shall 
#be governed by the third party's license and/or copyright agreement and not by this.
#
#TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, the Copyright Holders 
#DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR IMPLIED,
#INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY OR
#FITNESS FOR A PARTICULAR PURPOSE, WITH REGARD TO THE BENCHMARKS AND THE
#ACCOMPANYING DOCUMENTATION.  LICENSEE ACKNOWLEDGES AND AGREES THAT
#THERE ARE NO WARRANTIES, GUARANTIES, CONDITIONS, COVENANTS, OR
#REPRESENTATIONS BY Copyright Holders AS TO MARKETABILITY,
#FITNESS FOR A PARTICULAR PURPOSE, OR OTHER ATTRIBUTES, WHETHER EXPRESS
#OR IMPLIED (IN LAW OR IN FACT), ORAL OR WRITTEN.
#
#Licensee hereby agrees by accessing this source code that all benchmark
#scores related to this code must be certified by a company authorized by 
#Copyright Holders prior to publication in any media, form, distribution, 
#or other means of conveyance of information subject to the terms of the 
#Copyright Holders Member License Agreement and/or Alan R. Weiss and Rick Foos 
#Licensee Agreement.  
#
# Similar to ancient Unix command mkproto. Many versions of this are public
# around the net.
#
# Generates a file of C prototypes
# Additional information for Doxygen file definition added
# Add any type definitions to regular expressions below.
#
# To exclude a prototype, add whitespace before first definition.
# functions which start with static and extern are also excluded.
#

BEGIN {
  inheader=0;
  current_file="";
  if (headerdefine == "") {headerdefine = "PROTO_H"}
  if (headerdox == "") {headerdox = substr(headerdefine,1,match(headerdefine,/_/)-1);}
  if (headername == "") {headername = "proto.h"}
  print "#ifndef",headerdefine
  print "#define",headerdefine
  print ""
# Source directory specific doxygen tags
  print "/**"
  print " * @file "
  print " * @brief All prototypes grouped by file."
  print " *"
  print " * A reference file for all globally defined functions and procedures."
  print " *"
  print " * @remark This file is automatically generated with \"make proto\". DO NOT EDIT"
  print " */"
  print ""
  print "/** @addtogroup eembc_utilities Version 2 Benchmark Utilities"
  print " * @{ */"
  print "/** @addtogroup",headerdefine,headerdox,"Application Program Interface"
  print " * @{ */"
}

{
  if (FILENAME!=current_file) {
    print ""
    print "/* The following definitions come from ",FILENAME," */"
    print ""
    current_file=FILENAME
  }
  if (inheader) {
    if (match($0,"[)][ \t]*$")) {
      inheader = 0;
      printf "%s;\n",$0;
    } else {
      printf "%s\n",$0;
    }
    next;
  }
}

/^static|^extern/ || !/^[a-zA-Z]/ || /[;]/ {
  next;
}

!/^unsigned|^signed|^mode_t|^DIR|^user|^int|^float|^double|^char|^struct|^BOOL|^void|^time|^FILE|^long/ {
  next;
}


/[(].*[)][ \t]*$/ {
    printf "%s;\n",$0;
    next;
}

/[(]/ {
  inheader=1;
  printf "%s\n",$0;
  next;
}

END {
  print ""
# Source directory specific doxygen tags
  print "/** @} */"
  print "/** @} */"
  print "#endif /* ",headerdefine," */"
  print ""
}

