#!/bin/sh
# $Id: dumphint,v 1.1 2003/05/06 20:50:10 alexcher Exp $
# Linearized PDF hint formatting utility.

OPTIONS="-dSAFER -dDELAYSAFER"
while true
do
	case "$1" in
	-*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -ne 1 ]; then
	echo "Usage: `basename $0` input.pdf" 1>&2
	exit 1
fi

exec gs -q -dNODISPLAY $OPTIONS -- dumphint.ps "$1"
