#!/bin/sh
# $Id: ps2pdf 6300 2005-12-28 19:56:24Z giles $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
exec ps2pdf14 "$@"
