#!/bin/sh
# $Id: wftopfa 6300 2005-12-28 19:56:24Z giles $

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gs

exec $GS_EXECUTABLE -q -dNODISPLAY -- wftopfa.ps "$@"
